const shome = () => location.href="index.html";
const menu1 = () => location.href="info1.html";
const menu11 = () => location.href="info1.html";
const menu12 = () => location.href="info2.html";
// const menu13 = () => location.href="info3.html";
// const menu2 = () => location.href="program1.html";
// const menu21 = () => location.href="program1.html";
// const menu22 = () => location.href="program2.html";
// const menu23 = () => location.href="program3.html";
// const menu24 = () => location.href="program4.html";
// const menu25 = () => location.href="program5.html";
const menu13 = () => location.href="ready.html";
const menu2 = () => location.href="ready.html";
const menu21 = () => location.href="ready.html";
const menu22 = () => location.href="ready.html";
const menu23 = () => location.href="ready.html";
const menu24 = () => location.href="ready.html";
const menu25 = () => location.href="ready.html";
const menu3 = () => location.href="notice1.html";
const menu31 = () => location.href="notice1.html";
const menu32= () => location.href="faq1.html";