name: Deploy to Production

on: 
  push:
    branches:
      - main 
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Windows
        - win
        - macOS

jobs:
  build:
    runs-on: [self-hosted, win]
    
    steps:
      - name: Check OS
        run: echo ${{ runner.os }}
