name: Deploy to Production

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.HEOSUYEON_SSH_PRIVATE_KEY }}
        script: |
            whoami
            cd ${{ secrets.REPO_PATH }}
            git pull origin main
