name: Deploy to Production

on: [push]

jobs:
  build:
    name: Build
    runs-on: [self-hosted, win]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up SSH
        run: |
          mkdir -Force -Path ~/.ssh
          echo "${{ secrets.HEOSUYEON_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.REPO_PATH }}
            git pull origin main
          EOF
