name: Deploy to Production

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [self-hosted, win]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check os
        run: |
          echo "Current OS: $RUNNER_OS"
