name: Deploy to Production

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, some-self-hosted-runner]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check os
        run: echo ${{ matrix.os }}
