name: Deploy to Production

on: 
  push:
    branches:
      - main 
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Windows
        - win
        - macOS

jobs:
  build:
   name: build
   runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
   steps:
    - name: os check
      run: echo ${{ inputs.chosen-os }}
